typography_spectrum: 0.3535687041003257
color:
  brandStrength: 0.8125073171686381
  lightness: 0.4722642358392477
  saturation: 0.06270158849656582
  rhythmicContrast: 0.581449297722429
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.36507775099016726
analytics:
  google: UA-78762389-1
author:
  name: Antoine Despres-Bedward
  email: adbedward@icloud.com
name: Antoine Despres-Bedward
navigation:
  - name: My Thesis
    url: 'https://dt.athabascau.ca/jspui/handle/10791/43'
    type: external
  - name: Proud to be a public servant - Federal Youth Network
    url: 'https://youtu.be/NVJx57GAARE'
    type: external
title: ANTOINE DESPRES-BEDWARD
description: Design Learning that Excites!
