typography_spectrum: 0.5939371327403933
color:
  brandStrength: 0.7987902902532369
  lightness: 0.2091386397369206
  saturation: 0.9592126074712723
  rhythmicContrast: 0.3974423373583704
  brandColors:
    - '#1C1D21'
    - '#31353D'
    - '#445878'
    - '#92CDCF'
    - '#EEEFF7'
layout_spectrum: 0.6720799962058663
analytics:
  google: UA-78762389-1
author:
  name: Antoine Despres-Bedward
  email: adbedward@icloud.com
name: Antoine Despres-Bedward
navigation:
  - name: My Thesis
    url: 'https://dt.athabascau.ca/jspui/handle/10791/43'
    type: external
  - name: Proud to be a public servant - Federal Youth Network
    url: 'https://youtu.be/NVJx57GAARE'
    type: external
  - name: LinkedIn
    url: www.linkedin.com/in/antoinebedward
    type: external
title: ANTOINE DESPRES-BEDWARD
description: Design Learning that Excites!
