typography_spectrum: 0.8643305678851902
color:
  brandStrength: 0.7358286662492901
  lightness: 0.15505340998061
  saturation: 0.6557829652447253
  rhythmicContrast: 0.7015585771296173
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
layout_spectrum: 0.24358936632052064
analytics:
  google: UA-78762389-1
name: Antoine Despres-Bedward
navigation:
  - name: >-
      Comparing the effect of support on student satisfaction in online and
      face-to-face universities
    url: 'https://dt.athabascau.ca/jspui/handle/10791/43'
    type: external
title: ANTOINE DESPRES-BEDWARD
description: I Design Learning that Excites!
